<div class="w3-container">

    <h2 class="w3-left"><?php echo $this->board[0]['board_name']; ?></h2>
    <div class="w3-row">
        <div class="w3-col-2">
            <button id="subscribe-to-board" class="w3-btn w3-theme-gradient">Subscribe To Board</button>
            <br>
            <p class="w3-center" id="subscribe-message"></p>
        </div>
    </div>

    <script type="text/javascript">
        $('#subscribe-to-board').on('click', function() {
            let id = path => path.substring(path.lastIndexOf('/') + 1);
            let subOptions = 1

            $.ajax({
                type: "POST",
                url: "<?php echo $this->url('home/forum', [ 'action' => 'subscribe-to-board']); ?>",
                data: {
                    boardID: id('<?php echo $_SERVER['REQUEST_URI']; ?>'),
                    boardOptions: subOptions
                }
            }).done(function(response) {
                $('#subscribe-message').html(response);
            }).fail(function(failure) {
                $('#subscribe-message').html(failure);
            });
        });
    </script>
    <br>

<table class="w3-table-all">
    <tr>
        <th>Board Moderators</th>
        <th>Author</th>
        <th>Topic</th>
        <th>Posts</th>
        <th>Responses</th>
    </tr>

    <?php foreach ($this->board as $key => $value): ?>
        <tr>
            <td><?php echo $value['board_moderators']; ?></td>
            <td><?php echo $value['author']; ?></td>
            <td><?php echo $value['topic']; ?></td>
            <td><?php echo $value['posts']; ?></td>
            <td><?php echo $value['response']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
    <br>
    <div class="w3-row w3-left">
        <div class="w3-col-2">
            <button class="w3-btn w3-theme-gradient" id="post-new-topic">Post A New Topic</button>
            <button class="w3-btn w3-theme-gradient" id="reply-to-topic">Reply To A Topic</button>
        </div>

        <script type="text/javascript">
            $('#post-new-topic').on('click', function() {
                document.getElementById('post-new-topic-modal').style.display = 'block';
            });

            $('#reply-to-topic').on('click', function() {
                document.getElementById('reply-to-topic-modal').style.display = 'block';
            })
        </script>
    </div>

    <!-- modals -->
    <div class="w3-modal" id="post-new-topic-modal">
        <div class="w3-modal-content">
            <header class="w3-container w3-theme-gradient">
                <span onclick="document.getElementById('post-new-topic-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
                <h2>Post New Topic</h2>
            </header>

            <div class="w3-container">
                <br>
                <p></p>
                <div class="w3-row">
                    <label for="topic">Topic:</label>
                    <input type="text" id="topic" class="w3-input" placeholder="Topic">
                </div>

                <br>

                <div class="w3-row">
                    <label for="message">Message:</label>
                    <textarea class="w3-input" id="message">Message</textarea>
                </div>

                <br>

                <div class="w3-row">
                    <input type="radio" class="w3-radio" id="subscribe" value="1">
                    <label>Subscribe</label>
                    <br>
                </div>

                <div class="w3-row">
                    <button class="w3-btn w3-theme-gradient w3-right" id="post-topic-btn">Post Topic</button>
                </div>
            </div>

            <script type="text/javascript">
                $('#post-topic-btn').on('click', function() {
                    const boardIdPath = path => path.substring(path.lastIndexOf('/') + 1);

                    let topic = $('#topic').val();
                    let message = $('#message').val();
                    let subscribe = function() {
                        if ($('#subscribe').is(':checked')) {
                            return true;
                        } else {
                            return false;
                        }
                    }

                    $.ajax({
                        type: "POST",
                        url: "<?php echo $this->url('home/forum', ['action' => 'post-topic']); ?>",
                        data: {
                            boardId: boardIdPath('<?php echo $_SERVER['REQUEST_URI']; ?>'),
                            boardTopic: topic,
                            boardMessage: message,
                            boardSubscribe: subscribe()
                        }
                    }).done(function(response) {
                        $('#post-topic-footer').html("<p class=\"w3-center\">" + response + "</p>");
                    }).fail(function(msg) {
                        $('#post-topic-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                    })
                });
            </script>

            <br><br><br>
            <footer class="w3-container w3-theme-gradient" id="post-topic-footer">&nbsp;</footer>
        </div>
    </div>


    <div class="w3-modal" id="reply-to-topic-modal">
        <div class="w3-modal-content">
            <header class="w3-container w3-theme-gradient">
                <span onclick="document.getElementById('reply-to-topic-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
                <h2>Reply To A Topic</h2>
            </header>

            <div class="w3-container">


                <br><br>
                <table class="w3-table-all" id="reply-topics-table">
                    <tr>
                        <th>Author</th>
                        <th>Topic</th>
                        <th>Posts</th>
                        <th>Respond</th>
                    </tr>
                </table>

                <script type="text/javascript">
                    let id = path => path.substring(path.lastIndexOf('/') + 1);
                    const checked = [];

                    $.ajax({
                        type: "POST",
                        url: "<?php echo $this->url('home/forum', [ 'action' => 'get-topics' ]); ?>",
                        dataType: "json",
                        data: {
                            boardID: id("<?php echo $_SERVER['REQUEST_URI']; ?>")
                        }
                    }).done(function(response) {
                         $.each(response, function(key, value) {
                             $('#reply-topics-table').append("<tr><td class=\"board-author\">" + value.author + "</td><td class=\"board-topic\">" + value.topic + "</td><td class=\"board-post\">" + value.posts + "</td><td><input type=\"checkbox\" class=\"w3-input respond\"></td></tr>");
                         });

                         $(document).on('change', '.respond', function() {
                            $('#div-response').attr('style', 'display: block;');
                            let author, topic, post;

                            author = $(this).closest('tr').find('.board-author').html();
                            topic  = $(this).closest('tr').find('.board-topic').html();
                            post   = $(this).closest('tr').find('.board-post').html();

                            checked.push(author, topic, post);

                            $.ajax({
                                type: "POST",
                                url: "<?php echo $this->url('home/forum', [ 'action' => 'enable-reply']); ?>",
                                dataType: "json",
                                data: {
                                    getAuthor: checked.at(0),
                                    getTopic: checked.at(1),
                                    getPost: checked.at(2)
                                }
                            }).done(function(response) {
                                $('#responding-to-header').html("Responding to " + response.post + " By " + response.author);
                            });
                         });
                    }).fail(function(msg) {
                        $("#reply-to-topic-footer").html("<p class=\"w3-center\">Error retrieving topics</p>");
                    })
                </script>

                <br><br>
                <div class="w3-col l7" id="div-response" style="display: none;">
                    <p class="w3-left w3-border-all w3-theme-gradient" id="responding-to-header" style="text-shadow: 2px 2px 5px silver;"></p>
                    <textarea id="response" class="w3-input w3-border-black w3-border" style="width: 100%; height: 150px; resize: none;"></textarea>
                    <br>
                    <button class="w3-btn w3-theme-gradient" id="respond-to-post-btn">Respond</button>

                    <script type="text/javascript">
                        $('#respond-to-post-btn').on('click', function() {
                            $.ajax({
                                type: "POST",
                                url: "<?php echo $this->url('home/forum', [ 'action' => 'reply-to-topic']); ?>",
                                data: {
                                    boardID: id("<?php echo $_SERVER['REQUEST_URI']; ?>"),
                                    getResponse: $('#response').val()
                                }
                            }).done(function(msg) {
                                $('#reply-to-topic-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                            }).fail(function(msg) {
                                $('#reply-to-topic-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                            });
                        });
                    </script>
                </div>
            </div>

            <br><br><br>
            <footer class="w3-container w3-theme-gradient" id="reply-to-topic-footer">&nbsp;</footer>
        </div>
    </div>

</div>

<script type="text/javascript">
    const modal1 = document.getElementById('post-new-topic-modal');
    const modal2 = document.getElementById('reply-to-topic-modal');

    window.onclick = function(event) {
        if (event.target === modal1) {
            modal1.style.display = 'none';
        }

        if (event.target === modal2) {
            modal2.style.display = 'none';
        }
    }
</script>