<div class="w3-container">

    <h2 class="w3-left"><?php echo $this->board[0]['board_name']; ?></h2>
    <div class="w3-row">
        <div class="w3-col-2">
            <button id="subscribe-to-board" class="w3-btn w3-theme-gradient">Subscribe To Board</button>
            <br>
            <p class="w3-center" id="subscribe-message"></p>
        </div>
    </div>

    <script type="text/javascript">
        $('#subscribe-to-board').on('click', function() {
            let id = path => path.substring(path.lastIndexOf('/') + 1);
            let subOptions = 1

            $.ajax({
                type: "POST",
                url: "<?php echo $this->url('home/forum', [ 'action' => 'subscribe-to-board']); ?>",
                data: {
                    boardID: id('<?php echo $_SERVER['REQUEST_URI']; ?>'),
                    boardOptions: subOptions
                }
            }).done(function(response) {
                $('#subscribe-message').html(response);
            }).fail(function(failure) {
                $('#subscribe-message').html(failure);
            });
        });
    </script>
    <br>

<table class="w3-table-all">
    <tr>
        <th>Board Moderators</th>
        <th>Author</th>
        <th>Topic</th>
        <th>Posts</th>
    </tr>

    <?php foreach ($this->board as $key => $value): ?>
        <tr>
            <td><?php echo $value['board_moderators']; ?></td>
            <td><?php echo $value['author']; ?></td>
            <td><?php echo $value['topic']; ?></td>
            <td><?php echo $value['posts']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
    <br>
    <div class="w3-row w3-left">
        <div class="w3-col-2">
            <button class="w3-btn w3-theme-gradient" id="post-new-topic">Post A New Topic</button>
            <button class="w3-btn w3-theme-gradient" id="reply-to-topic">Reply To A Topic</button>
        </div>

        <script type="text/javascript">
            $('#post-new-topic').on('click', function() {
                document.getElementById('post-new-topic-modal').style.display = 'block';
            });
        </script>
    </div>

    <div class="w3-modal" id="post-new-topic-modal">
        <div class="w3-modal-content">
            <header class="w3-container w3-theme-gradient">
                <span onclick="document.getElementById('post-new-topic-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
                <h2>Post New Topic</h2>
            </header>

            <div class="w3-container">
                <br>
                <p></p>
                <div class="w3-row">
                    <label for="topic">Topic:</label>
                    <input type="text" id="topic" class="w3-input" placeholder="Topic">
                </div>

                <br>

                <div class="w3-row">
                    <label for="message">Message:</label>
                    <textarea class="w3-input" id="message">Message</textarea>
                </div>

                <br>

                <div class="w3-row">
                    <input type="radio" class="w3-radio" id="subscribe" value="1">
                    <label>Subscribe</label>
                    <br>
                </div>

                <div class="w3-row">
                    <button class="w3-btn w3-theme-gradient w3-right" id="post-topic-btn">Post Topic</button>
                </div>
            </div>

            <script type="text/javascript">
                $('#post-topic-btn').on('click', function() {
                    const boardIdPath = path => path.substring(path.lastIndexOf('/') + 1);

                    let topic = $('#topic').val();
                    let message = $('#message').val();
                    let subscribe = function() {
                        if ($('#subscribe').is(':checked')) {
                            return true;
                        } else {
                            return false;
                        }
                    }

                    $.ajax({
                        type: "POST",
                        url: "<?php echo $this->url('home/forum', ['action' => 'post-topic']); ?>",
                        data: {
                            boardId: boardIdPath('<?php echo $_SERVER['REQUEST_URI']; ?>'),
                            boardTopic: topic,
                            boardMessage: message,
                            boardSubscribe: subscribe()
                        }
                    }).done(function(response) {
                        $('#post-topic-footer').html("<p class=\"w3-center\">" + response + "</p>");
                    }).fail(function(msg) {
                        $('#post-topic-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                    })
                });
            </script>

            <br><br><br>
            <footer class="w3-container w3-theme-gradient" id="post-topic-footer">&nbsp;</footer>
        </div>
    </div>

</div>

<script type="text/javascript">
    const modal1 = document.getElementById('post-new-topic-modal');

    window.onclick = function(event) {
        if (event.target === modal1) {
            modal1.style.display = 'none';
        }
    }
</script>