<div class="w3-container">
    <p class="w3-center">Here you can chat with other users, browse profiles and customize your very own social profile. Just simply choose one of the below options to get started.</p>
    <br>

    <div class="w3-row">
        <div class="w3-col col-lg-2">
            <button id="browse-social-users" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('browse-online-users-modal').style.display = 'block';">Browse Online Users</button>
            &nbsp;
            <button id="pending-chat-requests" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('pending-chat-requests-modal').style.display = 'block';">Pending Chat Requests</button>
            &nbsp;
            <button id="current-chat-sessions" class="w3-btn w3-round w3-theme-gradient">Current Chats</button>
            &nbsp;
            <button id="view-user-profiles" class="w3-btn w3-round w3-theme-gradient">View User's Profiles</button>
            &nbsp;
            <button id="view-forums" class="w3-btn w3-round w3-theme-gradient">View Forums</button>
            &nbsp;
            <button id="pending-chat-requests" class="w3-btn w3-round w3-theme-gradient">Pending Chat Requests</button>
            &nbsp;
            <button id="create-profile" class="w3-btn w3-round w3-theme-gradient">Create Profile</button>
            &nbsp;
            <button id="edit-profile" class="w3-btn w3-round w3-theme-gradient">Edit Profile</button>
            &nbsp;
            <button id="delete-profile" class="w3-btn w3-round w3-theme-gradient">Delete Profile</button>
        </div>
    </div>
</div>


<!-- modals -->
<div id="browse-online-users-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('browse-online-users-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Current Users Online</h2>
        </header>

        <div class="w3-container">
            <p></p>
            <table class="w3-table-all" style="display: none; overflow: auto;" id="online-users-table">
                <tr>
                    <th>User</th>
                    <th>Message</th>
                    <th>Request Chat Session</th>
                </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('home/social', [ 'action' => 'view-online-users' ]); ?>",
                    dataType: "json"
                }).done(function(data) {
                    if (undefined !== data) {
                        $('#online-users-table').attr('style', 'display: block;');

                        $.each(data, function(key, value) {
                            $('#online-users-table').append("<tr><td class=\"chat-user\">" + value.username + "</td><td class=\"r-chat-msg\"><input class=\"w3-input w3-border\" name=\"message\" id=\"message\" placeholder=\"Message\">"
                                + "</td><td class=\"r-chat\"><input type=\"checkbox\" class=\"w3-check\" id=\"" + key + "\"></td></tr>");
                        });
                    } else {
                        $('#users-online-footer').html("<p class=\"w3-center\">No users online</p>");
                    }
                }).fail(function() {
                    $('#users-online-footer').html("<p class=\"w3-center\">Error fetching user list, please try again.</p>");
                })
            </script>
            <br><br>
            <button class="w3-button w3-round w3-hover-blue w3-right" id="send-chat-request-btn">Send Chat Request</button>

            <script type="text/javascript">
                $('#send-chat-request-btn').on('click', function() {
                    let checked = [];

                    $('#online-users-table input:checked').each(function() {
                        let user, message;

                        user = $(this).closest('tr').find('.chat-user').html();
                        message = $(this).closest('tr').find('#message').val();

                        checked.push(user, message);

                        $.ajax({
                            type: "POST",
                            url: "<?php echo $this->url('home/social', [ 'action' => 'send-chat-request' ]); ?>",
                            data: {
                                info: checked.join(", ")
                            }
                        }).done(function(msg) {
                            $('#users-online-footer').html("<p class=\"w3-center\">Chat Request Sent</p>");
                        }).fail(function(msg) {
                            $('#users-online-footer').html("<p class=\"w3-center\">Error sending chat request, please try again.</p>");
                        });
                    });
                });
            </script>

        </div>
        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="users-online-footer">&nbsp;</footer>
    </div>
</div>


<div id="pending-chat-requests-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('pending-chat-requests-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Pending Chat Requests</h2>
        </header>

        <div class="w3-container">
            <p></p>
            <table class="w3-table-all" style="display: none; overflow: auto;" id="pending-chat-requests-table">
               <tr>
                   <th>Recipient</th>
                   <th>Message</th>
                   <th>Date Sent</th>
                   <th>Chat Accepted (0 indicates the request is still pending)</th>
               </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                   type: "POST",
                   url: "<?php echo $this->url('home/social', [ 'action' => 'pending-chat-requests']); ?>",
                   dataType: "json"
                }).done(function(data) {
                    if (undefined !== data) {
                        $('#pending-chat-requests-table').attr('style', 'display: block;');

                        $.each(data, function(key, value) {
                            $('#pending-chat-requests-table').append("<tr><td>" + value.recipient + "</td><td>" + value.message + "</td><td>" + value.date_sent + "</td><td>" + value.chat_accepted + "</td></tr>");
                        });
                    } else {
                        $('#pending-chat-requests-footer').html("<p class=\"w3-center\">No pending chat requests were found.</p>");
                    }
                }).fail(function() {
                    $('#pending-chat-requests-footer').html("<p class=\"w3-center\">Error retrieving your pending chat requests, please try again.</p>");
                });
            </script>
        </div>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="pending-chat-requests-footer">&nbsp;</footer>
    </div>
</div>



<script type="text/javascript">
    const modal1 = document.getElementById('browse-online-users-modal');
    const modal2 = document.getElementById('pending-chat-requests-modal');


    window.onclick = function(event) {
        if (event.target === modal1) {
            modal1.style.display = 'none';
        }

        if (event.target === modal2) {
            modal2.style.display = 'none';
        }
    }
</script>