<div class="w3-container">
    <p class="w3-center">Here you can chat with other users, browse profiles and customize your very own social profile. Just simply choose one of the below options to get started.</p>
    <br>

    <div class="w3-bar w3-theme-gradient">
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('browse-social-users-tab');">Browse Social Users</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('pending-chat-requests-tab');">Pending Chat Requests</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('incoming-chat-requests-tab');">Incoming Chat Requests</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('current-chats-tab');">Current Chats</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('view-users-profile-tab');">View Profiles</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('view-forums-tab');">Forums</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('view-board-subscriptions-tab');">Board Subscriptions</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('create-profile-tab');">Create Profile</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('edit-profile-tab');">Edit Profile</button>
        <button class="w3-bar-item w3-button w3-theme-gradient" onclick="openSocialOption('delete-profile-tab');">Delete Profile</button>
    </div>

    <div id="browse-social-users-tab" class="w3-container social-options">
        <h2>Browse Social Users</h2>
        <button id="browse-social-users" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('browse-online-users-modal').style.display = 'block';">Browse Online Users</button>
    </div>

    <div id="pending-chat-requests-tab" class="w3-container social-options" style="display: none;">
        <h2>Pending Chat Requests</h2>
        <button id="pending-chat-requests" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('pending-chat-requests-modal').style.display = 'block';">Outgoing Chat Requests</button>
    </div>

    <div id="incoming-chat-requests-tab" class="w3-container social-options" style="display: none;">
        <h2>Incoming Chat Requests</h2>
        <button id="incoming-chat-requests" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('incoming-chat-requests-modal').style.display = 'block';">Incoming Chat Requests</button>
    </div>

    <div id="current-chats-tab" class="w3-container social-options" style="display: none;">
        <h2>Current Chats</h2>
        <button id="current-chat-sessions" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('current-chats-modal').style.display = 'block';">Current Chats</button>
    </div>

    <div id="view-users-profile-tab" class="w3-container social-options" style="display: none;">
        <h2>User Profiles</h2>
        <button id="view-user-profiles" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('view-profiles-modal').style.display = 'block';">View User's Profiles</button>
    </div>

    <div id="view-forums-tab" class="w3-container social-options" style="display: none;">
        <h2>Forums</h2>
        <button id="view-forums" class="w3-btn w3-round w3-theme-gradient" onclick="window.open('<?php echo $this->url('home/forum', [ 'action' => 'index' ]); ?>');">View Forums</button>
    </div>

    <div id="view-board-subscriptions-tab" class="w3-container social-options" style="display: none;">
        <h2>View Board Subscriptions</h2>
        <button id="view-board-subscriptions-btn" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('view-board-subscriptions-modal').style.display = 'block';">View Board Subscriptions</button>
    </div>

    <div id="create-profile-tab" class="w3-container social-options" style="display: none;">
        <h2>Create Profile</h2>
        <button id="create-profile" class="w3-btn w3-round w3-theme-gradient" onclick="document.getElementById('create-profile-modal').style.display = 'block';">Create Profile</button>
    </div>

    <div id="edit-profile-tab" class="w3-container social-options" style="display: none;">
        <h2>Edit Profile</h2>
        <button id="edit-profile" class="w3-btn w3-round w3-theme-gradient">Edit Profile</button>
    </div>

    <div id="delete-profile-tab" class="w3-container social-options" style="display: none;">
        <h2>Delete Profile</h2>
        <button id="delete-profile" class="w3-btn w3-round w3-theme-gradient">Delete Profile</button>
    </div>


</div>


<!-- modals -->
<div id="browse-online-users-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('browse-online-users-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Current Users Online</h2>
        </header>

        <div class="w3-container">
            <p></p>
            <table class="w3-table-all" style="display: none; overflow: auto;" id="online-users-table">
                <tr>
                    <th>User</th>
                    <th>Message</th>
                    <th>Request Chat Session</th>
                </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('home/social', [ 'action' => 'view-online-users' ]); ?>",
                    dataType: "json"
                }).done(function(data) {
                    if (undefined !== data) {
                        $('#online-users-table').attr('style', 'display: block;');

                        $.each(data, function(key, value) {
                            $('#online-users-table').append("<tr><td class=\"chat-user\">" + value.username + "</td><td class=\"r-chat-msg\"><input class=\"w3-input w3-border\" name=\"message\" id=\"message\" placeholder=\"Message\">"
                                + "</td><td class=\"r-chat\"><input type=\"checkbox\" class=\"w3-check\" id=\"" + key + "\"></td></tr>");
                        });
                    } else {
                        $('#users-online-footer').html("<p class=\"w3-center\">No users online</p>");
                    }
                }).fail(function() {
                    $('#users-online-footer').html("<p class=\"w3-center\">Error fetching user list, please try again.</p>");
                })
            </script>
            <br><br>
            <button class="w3-button w3-round w3-hover-blue w3-right" id="send-chat-request-btn">Send Chat Request</button>

            <script type="text/javascript">
                $('#send-chat-request-btn').on('click', function() {
                    let checked = [];

                    $('#online-users-table input:checked').each(function() {
                        let user, message;

                        user = $(this).closest('tr').find('.chat-user').html();
                        message = $(this).closest('tr').find('#message').val();

                        checked.push(user, message);

                        $.ajax({
                            type: "POST",
                            url: "<?php echo $this->url('home/social', [ 'action' => 'send-chat-request' ]); ?>",
                            data: {
                                info: checked.join(", ")
                            }
                        }).done(function(msg) {
                            $('#users-online-footer').html("<p class=\"w3-center\">Chat Request Sent</p>");
                        }).fail(function(msg) {
                            $('#users-online-footer').html("<p class=\"w3-center\">Error sending chat request, please try again.</p>");
                        });
                    });
                });
            </script>

        </div>
        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="users-online-footer">&nbsp;</footer>
    </div>
</div>


<div id="pending-chat-requests-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('pending-chat-requests-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Pending Chat Requests</h2>
        </header>

        <div class="w3-container">
            <p></p>
            <table class="w3-table-all" style="display: none; overflow: auto;" id="pending-chat-requests-table">
               <tr>
                   <th>Recipient</th>
                   <th>Message</th>
                   <th>Date Sent</th>
                   <th>Chat Accepted (0 indicates the request is still pending, 2 indicates accepted, 1 denied)</th>
               </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                   type: "POST",
                   url: "<?php echo $this->url('home/social', [ 'action' => 'pending-chat-requests' ]); ?>",
                   dataType: "json"
                }).done(function(data) {
                    if (undefined !== data) {
                        $('#pending-chat-requests-table').attr('style', 'display: block;');

                        $.each(data, function(key, value) {
                            $('#pending-chat-requests-table').append("<tr><td>" + value.recipient + "</td><td>" + value.message + "</td><td>" + value.date_sent + "</td><td>" + value.chat_accepted + "</td></tr>");
                        });
                    } else {
                        $('#pending-chat-requests-footer').html("<p class=\"w3-center\">No pending chat requests were found.</p>");
                    }
                }).fail(function() {
                    $('#pending-chat-requests-footer').html("<p class=\"w3-center\">Error retrieving your pending chat requests, please try again.</p>");
                });
            </script>
        </div>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="pending-chat-requests-footer">&nbsp;</footer>
    </div>
</div>


<div id="incoming-chat-requests-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('incoming-chat-requests-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Incoming Chat Requests</h2>
        </header>

        <div class="w3-container">
            <p></p>
            <table class="w3-table-all" style="display: none; overflow: auto;" id="incoming-chat-requests-table">
                <tr>
                    <th>Id</th>
                    <th>Sent By</th>
                    <th>Message</th>
                    <th>Date Sent</th>
                    <th>Chat Accepted (0 indicates not accepted, 1 approved, 2 denied)</th>
                    <th>Accept</th>
                    <th>Deny</th>
                </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('home/social', [ 'action' => 'incoming-chat-requests']); ?>",
                    dataType: "json"
                }).done(function(data) {
                    if (undefined !== data) {
                        $('#incoming-chat-requests-table').attr('style', 'display: block;');

                        $.each(data, function(key, value) {
                            $('#incoming-chat-requests-table').append("<tr><td class=\"cr-id\">" + value.id + "</td><td>" + value.sent_by + "</td><td>" + value.message + "</td><td>" + value.date_sent + "</td><td>" + value.chat_accepted + "</td>"
                                + "<td><input type=\"checkbox\" id=\"" + value.id + "\" class=\"w3-check\"></td><td><input type=\"checkbox\" id=\"" + value.id + "\" class=\"w3-check\"></td></tr>");
                        });
                    } else {
                        $('#incoming-chat-requests-footer').html("<p class=\"w3-center\">No incoming chat requests were found.</p>");
                    }
                }).fail(function() {
                    $('#incoming-chat-requests-footer').html("<p class=\"w3-center\">Error retrieving your incoming chat requests, please try again.</p>");
                });
            </script>
            <br><br>

            <button class="w3-button w3-round w3-hover-blue w3-right" id="deny-all-cr">Deny</button>
            <button class="w3-button w3-round w3-hover-blue w3-right" id="confirm-all-cr">Confirm</button>


            <script type="text/javascript">
                $('#confirm-all-cr').on('click', function() {
                   let checked = [];

                    $('#incoming-chat-requests-table input:checked').each(function() {
                        let chatAccepted, crId;

                        crId = $(this).closest('tr').find('.cr-id').html();
                        chatAccepted = 1;

                        checked.push(crId, chatAccepted);

                        $.ajax({
                            type: "POST",
                            url: "<?php echo $this->url('home/social', [ 'action' => 'accept-chat-request' ]); ?>",
                            data: {
                                info: checked.join(', ')
                            }
                        }).done(function(msg) {
                            $('#incoming-chat-requests-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                            $('#incoming-chat-requests-table input:checked').prop('checked', false);
                        }).fail(function(msg) {
                            $('#incoming-chat-requests-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                        })
                    });
                });

                $('#deny-all-cr').on('click', function() {
                   let checked = [];

                   $('#incoming-chat-requests-table input:checked').each(function() {
                       let chatDenied, crId;

                       crId = $(this).closest('tr').find('.cr-id').html();
                       chatDenied = 1;

                       checked.push(crId, chatDenied);

                       $.ajax({
                           type: "POST",
                           url: "<?php echo $this->url('home/social', [ 'action' => 'deny-chat-request' ]); ?>",
                           data: {
                               info: checked.join(', ')
                           }
                       }).done(function(msg) {
                           $('#incoming-chat-requests-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                           $('#incoming-chat-requests-table input:checked').prop('checked', false);
                       }).fail(function(msg) {
                           $('#incoming-chat-requests-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                       })
                   })
                });
            </script>
        </div>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="incoming-chat-requests-footer">&nbsp;</footer>
    </div>
</div>


<div id="current-chats-modal" class="w3-modal" >
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('current-chats-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Current Chats</h2>
        </header>

        <div class="w3-container">
            <p></p>

            <table class="w3-table-all" style="display: none; overflow: auto;" id="current-chats-table">
                <tr>
                    <th>Room Title</th>
                    <th>Room Members</th>
                    <th>Room Moderators</th>
                    <th>Room Transcript</th>
                </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('home/social', [ 'action' => 'current-chats']); ?>",
                    dataType: "json"
                }).done(function(data) {
                    if (undefined !== data) {
                        $('#current-chats-table').attr('style', 'display: block;');

                        $.each(data, function(key, value) {
                           $('#current-chats-table').append("<tr><td>" + value.room_title + "</td><td>" + value.room_members + "</td><td>" + value.room_moderators + "</td><td>" + value.room_transcript + "</td></tr>");
                        });
                    } else {
                        $('#current-chats-footer').html("<p class=\"w3-center\">You aren't any members of chat room</p>");
                    }
                }).fail(function() {
                    $('#current-chats-footer').html("<p class=\"w3-center\">Error retrieving chat rooms, please try again.</p>");
                })
            </script>
        </div>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="current-chats-footer">&nbsp;</footer>
    </div>
</div>


<div id="view-profiles-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('view-profiles-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>View User Profiles</h2>
        </header>

        <div class="w3-container">
            <p>Criteria</p>
            <div class="w3-row">
                <div class="w3-col l2">
                    <label for="location">By Location:</label>
                    <input type="text" class="w3-input w3-border-black w3-round" id="location">
                </div>
            </div>

            <p></p>

            <div class="w3-row">
                <div class="w3-col l2">
                    <label for="username">By Username:</label>
                    <input type="text" class="w3-input w3-border-black w3-round" id="username">
                </div>
            </div>

            <p></p>

            <div class="w3-row">
                <div class="w3-col l2">
                    <label for="real_name">By Name:</label>
                    <input type="text" class="w3-input w3-border-black w3-round" id="real_name">
                </div>
            </div>

            <button id="search" class="w3-btn w3-theme-gradient w3-right">Search Profiles</button>

            <br><br><br><br>
            <p class="w3-left" id="profile-table-header" style="display: none;">Profiles Found:</p>
            <br><br>&nbsp;
            <table id="user-profiles-table" style="display: none; overflow: auto;" class="w3-table-all">
                <tr>
                    <th>Username</th>
                    <th>Real Name</th>
                    <th>Location</th>
                    <th>Avatar</th>
                    <th>Bio</th>
                </tr>
            </table>

            <script type="text/javascript">
                $('#search').on('click', function() {
                    if ($('#location').val() != "") {
                        let location = $('#location').val();

                        $.ajax({
                           type: "POST",
                           url: "<?php echo $this->url('home/social', [ 'action' => 'view-user-profiles' ]); ?>",
                           dataType: "json",
                           data: {
                               loc: location
                           }
                        }).done(function(data) {
                            if (undefined !== data) {
                                $('#profile-table-header').attr('style', 'display: block;');
                                $('#user-profiles-table').attr('style', 'display: block;');

                                $.each(data, function(key, value) {
                                   $('#user-profiles-table').append("<tr><td>"  + value.username  + "</td><td>" + value.real_name + "</td><td>" + value.location + "</td><td><img src=<?php echo $this->basePath(); ?>/profiles/" + value.username + "/avatar/" + value.avatar + " class=\"w3-card-4\" style=\"width: 150px; height: 150px; \"></td><td>" + value.bio + "</td></tr>");
                                });
                            }
                        });
                    } else if ($('#username').val() != "") {
                        let username = $('#username').val();

                        $.ajax({
                            type: "POST",
                            url: "<?php echo $this->url('home/social', [ 'action' => 'view-user-profiles' ]); ?>",
                            dataType: "json",
                            data: {
                                user: username
                            }
                        }).done(function(data) {
                            if (undefined !== data) {
                                $('#profile-table-header').attr('style', 'display: block;');
                                $('#user-profiles-table').attr('style', 'display: block;');

                                $.each(data, function(key, value) {
                                    $('#user-profiles-table').append("<tr><td>"  + value.username  + "</td><td>" + value.real_name + "</td><td>" + value.location + "</td><td><img src=<?php echo $this->basePath(); ?>/profiles/" + value.username + "/avatar/" + value.avatar + " class=\"w3-card-4\" style=\"width: 150px; height: 150px; \"></td><td>" + value.bio + "</td></tr>");
                                });
                            }
                        });
                    } else if ($('#real_name').val() != "") {
                        let realName = $('#real_name').val();

                        $.ajax({
                            type: "POST",
                            url: "<?php echo $this->url('home/social', [ 'action' => 'view-user-profiles' ]); ?>",
                            dataType: "json",
                            data: {
                                name: realName
                            }
                        }).done(function(data) {
                            if (undefined !== data) {
                                $('#profile-table-header').attr('style', 'display: block;');
                                $('#user-profiles-table').attr('style', 'display: block;');

                                $.each(data, function(key, value) {
                                    $('#user-profiles-table').append("<tr><td>"  + value.username  + "</td><td>" + value.real_name + "</td><td>" + value.location + "</td><td><img src=<?php echo $this->basePath(); ?>/profiles/" + value.username + "/avatar/" + value.avatar + " class=\"w3-card-4\" style=\"width: 150px; height: 150px; \"></td><td>" + value.bio + "</td></tr>");
                                });
                            }
                        });
                    } else {
                        $('#view-profiles-footer').html("<p class=\"w3-center\">Invalid criteria provided.</p>");
                        return;
                    }
                });
            </script>
        </div>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="view-profiles-footer">&nbsp;</footer>
    </div>
</div>


<div id="view-board-subscriptions-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('view-board-subscriptions-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Board Subscriptions</h2>
        </header>

        <div class="w3-container">
            <p></p>
            <table class="w3-table-all" style="display: none; white-space: nowrap; overflow: auto;" id="board-subscriptions-table">
                <tr>
                    <th>Board</th>
                    <th>Topic</th>
                    <th>Posts</th>
                </tr>
            </table>

            <script type="text/javascript">
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('home/social', ['action' => 'view-board-subscriptions']); ?>",
                    dataType: "json"
                }).done(function(response) {
                    if (undefined !== response) {
                        $('#board-subscriptions-table').attr('style', 'display: block;');

                        $.each(response, function(key, value) {
                           $('#board-subscriptions-table').append("<tr><td>" + value.board_name + "</td><td>" + value.topic + "</td><td>" + value.posts + "</td></tr>");
                        });
                    }
                }).fail(function() {
                    $('#view-board-subscriptions-footer').html("<p class=\"w3-center\">Error retrieving your board subscriptions.</p>");
                });
            </script>
        </div>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="view-board-subscriptions-footer">&nbsp;</footer>
    </div>
</div>


<div id="create-profile-modal" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container w3-theme-gradient">
            <span onclick="document.getElementById('create-profile-modal').style.display = 'none';" class="w3-button w3-display-topright w3-theme-gradient">&times;</span>
            <h2>Create Your Profile</h2>
        </header>

        <div class="w3-container">
            <p>Fill out the following to complete your profile:</p>

            <br><br>

            <form method="post" name="profile-form" id="profile-form" enctype="multipart/form-data">
            <div class="w3-row">
                <div class="w3-col l2">
                    <label for="real-name">Real Name</label>
                    <input type="text" id="real-name" class="w3-input">
                </div>
            </div>

            <br><br>

            <div class="w3-row">
                <div class="w3-col l2">
                    <label for="profile-location">Location</label>
                    <input type="text" id="profile-location" class="w3-input">
                </div>
            </div>

            <br><br>

            <div class="w3-row">
                <div class="w3-col l2">
                    <label for="profile-avatar">Avatar</label>
                        <input type="file" name="profile-avatar" id="profile-avatar" class="w3-input" accept="image/png, image/jpeg">
                    </div>
                </div>

            <br><br>

            <div class="w3-row">
                <div class="w3-col l4">
                    <label for="profile-bio">Bio</label>
                    <textarea id="profile-bio" class="w3-input"></textarea>
                </div>
            </div>
            </form>

            <br><br>
            <div class="w3-row w3-right">
                <div class="w3-col l2">
                    <button id="submit-profile" class="w3-btn w3-theme-gradient">Make Profile</button>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $('input[type="file"]').on('change', function() {
                let file = document.getElementById('profile-avatar').files[0];
                let formData = new FormData();
                formData.append("file", file);

                $.ajax({
                    type: "POST",
                    processData: false,
                    contentType: false,
                    url: "<?php echo $this->url('home/profile', [ 'action' => 'upload-profile-avatar' ]); ?>",
                    data: formData
                }).done(function(msg) {
                    $('#create-profile-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                }).fail(function(msg) {
                    $('#create-profile-footer').html("<p class=\"w3-center\">" + msg + "</p>");
                });
            });

            $('#submit-profile').on('click', function() {
                let real_name, location, bio;

                real_name = $('#real-name').val();
                location  = $('#profile-location').val();
                bio       = $('#profile-bio').val();

                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('home/profile', ['action' => 'make-profile']); ?>",
                    data: {
                        profileRealName: real_name,
                        profileLocation: location,
                        profileBio: bio,
                        profileAvatar: $('#profile-avatar').val().replace(/C:\\fakepath\\/i, '')
                    }
                });
            });
        </script>

        <br><br><br>
        <footer class="w3-container w3-theme-gradient" id="create-profile-footer">&nbsp;</footer>
    </div>
</div>

<script type="text/javascript">
    function openSocialOption(socialOption) {
        let i;
        let x = document.getElementsByClassName("social-options");

        for (i = 0; i < x.length; i++) {
            x[i].style.display = 'none';
        }

        document.getElementById(socialOption).style.display = 'block';
    }


    const modal1 = document.getElementById('browse-online-users-modal');
    const modal2 = document.getElementById('pending-chat-requests-modal');
    const modal3 = document.getElementById('incoming-chat-requests-modal');
    const modal4 = document.getElementById('current-chats-modal');
    const modal5 = document.getElementById('view-profiles-modal');
    const modal6 = document.getElementById('view-board-subscriptions-modal');
    const modal7  = document.getElementById('create-profile-modal');

    window.onclick = function(event) {
        if (event.target === modal1) {
            modal1.style.display = 'none';
        }

        if (event.target === modal2) {
            modal2.style.display = 'none';
        }

        if (event.target === modal3) {
            modal3.style.display = 'none';
        }

        if (event.target === modal4) {
            modal4.style.display = 'none';
        }

        if (event.target === modal5) {
            modal5.style.display = 'none';
        }

        if (event.target === modal6) {
            modal6.style.display = 'none';
        }

        if (event.target === modal7) {
            modal7.style.display = 'none';
        }
    }
</script>