<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Kevin Benitez - Life Coach')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/w3.css'); ?>
	
	    
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-light-blue.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
		
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery-3.5.1.min.js'); ?>

        <script type="text/javascript">
            $(document).ready(function() {
                let idleTimer = null;
                let warningTimer = null;
                let timeoutWarning = 840000;

                $('*').bind('mousemove click mouseup keydown keypress keyup submit change mouseenter scroll resize dblclick', function() {
                    clearTimeout(warningTimer);
                    clearTimeout(idleTimer);
                    
                    warningTimer = setTimeout(warning, timeoutWarning);

                    idleTimer = setTimeout(function() {
                        document.getElementById('timeout-modal').style.display = 'none';
                        window.location = "<?php echo $this->url('home/logout', array('action' => 'index')); ?>";
                    }, 900000);
                });
                
                function warning() {
                     document.getElementById('timeout-modal').style.display = 'block';
                }

               $('body').trigger('mousemove');
            });
        </script>
        
        <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" data-integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" data-crossorigin="anonymous"></script>
            
        <style>
            html, body, h1, h2, h3, h4, h5 {
                font-family: "Open Sans", sans-serif;
            } 
            
            .w3-theme-gradient {
                color: #000 !important;
                background: -webkit-linear-gradient(top,#64B5F6 25%,#42A5F5 75%);
            }
            
            .w3-theme-gradient {
                color: #000 !important;
                background: -moz-linear-gradient(top,#64B5F6 25%,#42A5F5 75%);
            }
    
            .w3-theme-gradient {
                color: #000 !important;
                background: -o-linear-gradient(top,#64B5F6 25%,#42A5F5 75%);
            }
            
            .w3-theme-gradient {
                color: #000 !important;
                background: -ms-linear-gradient(top,#64B5F6 25%,#42A5F5 75%);
            }
            
            .w3-theme-gradient {
                color: #000 !important;
                background: linear-gradient(top,#64B5F6 25%,#42A5F5 75%);
            }
            
            .upload-btn-wrapper {
                position: relative;
                overflow: hidden;
                display: inline-block;
            }
            
            .btn {
                border: thin solid #ffffff;
                color: #ffffff !important;
                background-color: #64B5F6;
                padding: 8px 20px;
                border-radius:  8px;
                font-size: 16px;
            }
            
            .upload-btn-wrapper input[type=file] {
                font-size: 100px;
                position: absolute;
                left: 0;
                top: 0;
                opacity: 0;
            }
        </style>
        

    </head>
    
    <body>
    
        <div class="w3-modal" id="timeout-modal">
            <div class="w3-modal-content w3-card-4 w3-round">
                <header class="w3-container">
                    <span onclick="document.getElementById('timeout-modal').style.display = 'none'" class="w3-button w3-display-topright">&times;</span>
                </header>
                
                <br><br>
                
                <div class="w3-container">
                    <h2 class="w3-center">You are about to be logged out due to inactivity in one minute.</h2>
                </div>
            </div>
        </div>
    
       <div class="w3-top">
       	   <div class="w3-bar w3-theme-gradient w3-wide w3-padding w3-card">
       	   		<a href="<?php echo $this->url('home', array('action' => 'index')); ?>" class="w3-bar-item w3-button w3-hover-blue">Home</a>
       	   		
       	   		<div class="w3-right w3-hide-small">
       	   			<div class="w3-dropdown-hover">
       	   				<button class="w3-button w3-theme-gradient w3-wide">Articles</button>
       	   				<div class="w3-dropdown-content w3-bar-block w3-border w3-theme-gradient">
				            <?php foreach ($this->articles as $value):  ?>
                                <a href="<?php echo $this->url('home/articles', array('article_id' => $value['article_id'])); ?>" class="w3-bar-item w3-button w3-hover-blue"><?php echo $value['title']; ?></a>
				            <?php endforeach; ?>
       	   				</div>
       	   			</div>
       	   			<a href="<?php echo $this->url('home/user', array('action' => 'messages')); ?>" class="w3-bar-item w3-button w3-hover-blue" title="Store">Your Messages</a>
       	   			<a href="<?php echo $this->url('home/user', array('action' => 'appointments')); ?>" class="w3-bar-item w3-button w3-hover-blue" title="Items">Your Appointments</a>
                    <a href="<?php echo $this->url('home/social', array('action' => 'index')); ?>" class="w3-bar-item w3-button w3-hover-blue" title="Social">Social</a>
       	   			<a href="<?php echo $this->url('home/logout', array('action' => 'index')); ?>" class="w3-bar-item w3-button w3-hover-blue" title="Logout">Logout</a>
       	   		</div>
       	   </div>
       </div>
       
       
       <br><br><br><br><br><br>
       
       <header class="w3-display-container w3-content w3-wide" style="max-width: 1500px;" id="home">
       		<div class="w3-display-middle w3-margin-top w3-center">
       		    <?php if (!empty($this->user)): ?>
       		       <h1 class="w3-xxlarge w3-text-black">Welcome back <?php echo $this->user; ?></h1>
       		    <?php else: ?>
       			<?php header('Location: /login'); exit; ?>
       			</p>
       			<?php endif; ?>
       		</div>
       </header> 
       
       <br><br><br><br><br><br>
       <div class="w3-content w3-padding" style="max-width: 1564px;">
       	   <?php echo $this->content; ?>
       </div>
      
     <br><br>
    <footer class="w3-container w3-bottom w3-theme-gradient w3-padding-tiny w3-margin-0">
 	   <p class="w3-center">&copy; <?php echo date('Y'); ?> Kevin Benitez. All Rights Reserved.</p>
 	</footer>  
   </body>
</html>